version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: /

    steps:
      - checkout

      - run:
          name: Hello, World!
          command: echo "Hello, World!"

workflows:
  version: 2
  build:
    jobs:
      - build
